services:
  ristwatch:
    build: .
    image: ristwatch:dev
    container_name: ristwatch-dev
    restart: unless-stopped
    environment:
      RISTWATCH_CONFIG_DIR: /config
      RISTWATCH_RIST_ENABLED: "true"
      RISTWATCH_PROFILE: "1"
    ports:
     - "18081:8080/tcp"
     - "2030:2030/udp"
     - "2031:2031/udp"
     - "5556:5556/udp"
    volumes:
      - ./.local/config:/config
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

